### ISSUE TITLE
Manual Map Crashing

### ISSUE THREAD

**Issue by 0x597575746F** [Broihon/GH-Injector-Library#18] opened 2022-02-22 03:36 UTC
LoadLibrary works fine but Manual Map crashes the target process. Even with an minimal dllmain with only `return TRUE;` inside crashes for some reason.

Library/GUI Version: 4.4

Options

• NtCreateThread
• Erase PEH
• Run DllMain
• Resolve Delay Imports
• Execute TLS
• Set Page Protections
• Enable exceptions
• Initialize security cookie

OS

Edition: Windows 10 Home Single Language
Version: 21H2
OS build: 19044.1526

**Comment by 0x597575746F** [comment] 2022-02-25 18:28
It worked before I restarted my system for a windows update. I don't remember what version it was or what it changed.

GH Injector returns a successful injection and my DLLMain doesn't contain anything. Load Library works regardless if the DLLMain contains a thread start function or not.

```
BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fdwReason, LPVOID lpReserved){
	return TRUE; 
}
```

**Comment by Broihon** [comment] 2022-02-25 20:39
Have you tried 4.5 instead of 4.4?

**Comment by Broihon** [comment] 2022-02-25 23:49
Tested 19044.1526 (both x64 and wow64) and couldn't reproduce the issue with version 4.5 and manual mapping. Update to 4.5 and try again.

**Comment by Broihon** [comment] 2022-03-10 12:03
Closing this since 4.4 is deprecated and I can't replicate the issue with 4.5 or 4.6 on 19044.1526. If the same issue occurs with 4.6 please reopen the issue.

**Closed by Broihon** 2022-03-10 12:03 UTC
